version: '2.4'

services:
  db:
    image: postgres:13.2-alpine
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
    env_file:
      - db.env

  app:
    image: nextcloud:21.0-fpm-alpine
    restart: always
    volumes:
      - nextcloud:/var/www/html
      - /media/ncdata/data:/var/www/html/data:rw
    env_file:
      - nc.env
    depends_on:
      - db

  web:
    build: ./web
    restart: always
    ports:
      - 443:443
    volumes:
      - nextcloud:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  nextcloud:
